sudo: required
dist: trusty
addons:
  apt:
    packages:
    - wget
    - curl
    - rpm
language: ruby
rvm:
- 2.1.5
env:
- PACKAGE_TARGET=deb
- PACKAGE_TARGET=rpm
install: bundle install
script:
- make
deploy:
  - provider: bintray
    file: ".bintray/deb.json"
    user: patdowney
    key:
      secure: p4OpM5LxQ4hvGcxn/kuB2WUjX8GT0Qnkqm9FXGw1ahHVizKioGRruiL74aaIZ7zM0eu82+cAyDw0kaWLyhVT3f9Mey4cZijjA1JSRlnaomqvW7flCb1KuOmMci7sW47vAf6Szzv1wBiZox7itFcsvZM3tvkTO8A5wflZwwX/Tt2lQCimvjajIcEv4pO8ug2SJITEW4EvFWWxpz9Tq4kUI3gNMbgI5uiAx//aRwTttHf98kucLi75fsWR7U4S3Rbx2fXld30u9VIxjVBrjndojn5jLMacoAwr1RGkeUMCynM0fCn6KTodknlZg64BkxtFx5OR0KVmQVg2Pmdj8PMjgF5LNASZ+31Sh0wLNEZ21Lg9brz17I++lq9ZZ30PDinmhL1hmnRiGN9oc/25Xh2fkxpyI7yS9x337p7Dy/2HQiNySuo1fzyn/juQ73vwjHYPZQeoI0+DGVlvJUGgowtgDWud65yn/C0OAjb1Iz1tKlk2LQAwcnucutnLK7gZ6aMbR45Rlz+OJCpa9JQmOdZ0RI4QD2WNz0pFnovrhLnpc/FJ2irCqZToeVflw7pVK39F5f2wixR6jAlLxutJ2uKz3TQRY1b6e/pe6wjwK0pE1Djr3/y9ByaK374Ge6Sf9Xt0ksSSRHyYtaFkZtzC4reS5pxKBV89hyQ1J0A93OcWTdc=
    on:
      condition: "$PACKAGE_TARGET = deb"
  - provider: bintray
    file: ".bintray/rpm.json"
    user: patdowney
    key:
      secure: p4OpM5LxQ4hvGcxn/kuB2WUjX8GT0Qnkqm9FXGw1ahHVizKioGRruiL74aaIZ7zM0eu82+cAyDw0kaWLyhVT3f9Mey4cZijjA1JSRlnaomqvW7flCb1KuOmMci7sW47vAf6Szzv1wBiZox7itFcsvZM3tvkTO8A5wflZwwX/Tt2lQCimvjajIcEv4pO8ug2SJITEW4EvFWWxpz9Tq4kUI3gNMbgI5uiAx//aRwTttHf98kucLi75fsWR7U4S3Rbx2fXld30u9VIxjVBrjndojn5jLMacoAwr1RGkeUMCynM0fCn6KTodknlZg64BkxtFx5OR0KVmQVg2Pmdj8PMjgF5LNASZ+31Sh0wLNEZ21Lg9brz17I++lq9ZZ30PDinmhL1hmnRiGN9oc/25Xh2fkxpyI7yS9x337p7Dy/2HQiNySuo1fzyn/juQ73vwjHYPZQeoI0+DGVlvJUGgowtgDWud65yn/C0OAjb1Iz1tKlk2LQAwcnucutnLK7gZ6aMbR45Rlz+OJCpa9JQmOdZ0RI4QD2WNz0pFnovrhLnpc/FJ2irCqZToeVflw7pVK39F5f2wixR6jAlLxutJ2uKz3TQRY1b6e/pe6wjwK0pE1Djr3/y9ByaK374Ge6Sf9Xt0ksSSRHyYtaFkZtzC4reS5pxKBV89hyQ1J0A93OcWTdc=
    on:
      condition: "$PACKAGE_TARGET = rpm"
